# -------------------------------------------------------------------------
# Definitions
# -------------------------------------------------------------------------

stages:
  - build
  - test
  - variants

# variables:
#  CI_DEBUG_TRACE: "true"

# Incude templates
include:
  - '/.gitlab-ci/build-templates.yml'
  - '/.gitlab-ci/test-templates.yml'
  - '/.gitlab-ci/variants-templates.yml'

# -------------------------------------------------------------------------
# Build stage
# -------------------------------------------------------------------------

# Debian OS Targets
#------------------

debian 9 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "debian:9"
    OS_NAME: "debian"
    OS_VERSION: "9.0"
    OS_ARCH: "amd64"
    OS_EXTRA_PACKAGES: "byacc flex"

debian 10 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "debian:10"
    OS_NAME: "debian"
    OS_VERSION: "10"
    OS_ARCH: "amd64"
    OS_EXTRA_PACKAGES: "flex"

debian 10 i386 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "i386/debian:10"
    OS_NAME: "debian"
    OS_VERSION: "10"
    OS_ARCH: "i386"
    OS_EXTRA_PACKAGES: "byacc flex"

debian 11 build:
  extends: .debian_build
  tags:
    - docker
  variables:
    OS_IMAGE: "debian:11"
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_ARCH: "amd64"
    OS_EXTRA_PACKAGES: ""

debian 11 i386 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "i386/debian:11"
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_ARCH: "i386"
    OS_EXTRA_PACKAGES: "byacc flex"

debian 11 armel build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "arm32v5/debian:11"
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_ARCH: "armel"
    OS_EXTRA_PACKAGES: "byacc flex"

debian 11 armhf build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "arm32v7/debian:11"
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_ARCH: "armhf"
    OS_EXTRA_PACKAGES: "byacc flex"

debian 11 arm64 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "arm64v8/debian:11"
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_ARCH: "arm64"
    OS_EXTRA_PACKAGES: "byacc flex"

# Ubuntu OS Targets
#------------------

ubuntu 18.04 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "ubuntu:18.04"
    OS_NAME: "ubuntu"
    OS_VERSION: "bionic"
    OS_ARCH: "binary-amd64"
    OS_EXTRA_PACKAGES: "byacc"

ubuntu 20.04 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "ubuntu:20.04"
    OS_NAME: "ubuntu"
    OS_VERSION: "focal"
    OS_ARCH: "binary-amd64"
    OS_EXTRA_PACKAGES: "byacc"

ubuntu 22.04 build:
  extends: .debian_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    OS_IMAGE: "ubuntu:22.04"
    OS_NAME: "ubuntu"
    OS_VERSION: "jammy"
    OS_ARCH: "binary-amd64"
    OS_EXTRA_PACKAGES: "byacc flex"

# RPM OS Targets
#---------------

centos 7 build:
  extends: .rpmos_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_IMAGE: "centos:7.9.2009"
    RPMOS_OS: "centos"
    RPMOS_VERSION: "7"
    RPMOS_ARCH: "x86_64"
    RPMOS_REPOS: ""

almalinux 8 build:
  extends: .rpmos_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_IMAGE: "almalinux:8"
    RPMOS_OS: "almalinux"
    RPMOS_VERSION: "8"
    RPMOS_ARCH: "x86_64"
    RPMOS_REPOS: "--enablerepo=powertools,epel"

almalinux 9 build:
  extends: .rpmos_build
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_IMAGE: "almalinux:9"
    RPMOS_OS: "almalinux"
    RPMOS_VERSION: "9"
    RPMOS_ARCH: "x86_64"
    RPMOS_REPOS: "--enablerepo=crb"

# -------------------------------------------------------------------------
# Test stage
# -------------------------------------------------------------------------

# CentOS
#-------

centos 7 test:
  extends: .rpmos_test
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_OS: "centos"
    RPMOS_VERSION: "7"
    RPMOS_IMAGE: "centos:7"
    RPMOS_ARCH: "x86_64"
    RPMOS_UUID: "NE-CE-07-X1"
  needs: ["centos 7 build"]

almalinux 8 test:
  extends: .rpmos_test
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_OS: "almalinux"
    RPMOS_VERSION: "8"
    RPMOS_IMAGE: "almalinux:8"
    RPMOS_ARCH: "x86_64"
    RPMOS_UUID: "NE-CE-08-X1"
  needs: ["almalinux 8 build"]

# -------------------------------------------------------------------------
# Variants stage
# -------------------------------------------------------------------------

# CentOS
#-------

clearos 7 variant:
  extends: .rpmos_variants
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_OS_SOURCE: "centos"
    RPMOS_OS: "clearos"
    RPMOS_VERSION: "7"
    RPMOS_IMAGE: "centos:7"
    RPMOS_ARCH: "x86_64"
  needs: ["centos 7 test"]

nethserver 7 variant:
  extends: .rpmos_variants
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_OS_SOURCE: "centos"
    RPMOS_OS: "nethserver"
    RPMOS_VERSION: "7"
    RPMOS_IMAGE: "centos:7"
    RPMOS_ARCH: "x86_64"
  needs: ["centos 7 test"]

rhel 7 variant:
  extends: .rpmos_variants
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_OS_SOURCE: "centos"
    RPMOS_OS: "rhel"
    RPMOS_VERSION: "7"
    RPMOS_IMAGE: "centos:7"
    RPMOS_ARCH: "x86_64"
  needs: ["centos 7 test"]

rhel 8 variant:
  extends: .rpmos_variants
  tags:
    - docker
  only:
    - tags
    - web
  variables:
    RPMOS_OS_SOURCE: "almalinux"
    RPMOS_OS: "rhel"
    RPMOS_VERSION: "8"
    RPMOS_IMAGE: "almalinux:8"
    RPMOS_ARCH: "x86_64"
  needs: ["almalinux 8 test"]
